base_model: meta-llama/Llama-3.1-8B-Instruct
model_type: LlamaForCausalLM
tokenizer_type: AutoTokenizer

trust_remote_code: true

load_in_8bit: false
load_in_4bit: false

datasets:
  - path: data/axolotl/en-AU_Sarcasm_Reddit.jsonl
    type: chat_template
    roles_to_train: ["user", "assistant"]
    train_on_eos: all

dataset_prepared_path: last_run_prepared
val_set_size: 0
output_dir: /scratch/users/k24053411/axolotl/llama/en-AU_Sarcasm_Reddit_adapter
resume_from_checkpoint:

model_config:
  output_router_logits: true

adapter: lora
lora_model_dir:

sequence_len: 512
sample_packing: true
pad_to_sequence_len: false

lora_r: 16
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 1
num_epochs: 5
optimizer: adamw_torch
lr_scheduler: cosine
learning_rate: 2e-5

bf16: true
tf32: false

gradient_checkpointing: false
logging_steps: 10
flash_attention: false

loss_watchdog_threshold: 10.0
loss_watchdog_patience: 3

warmup_ratio: 0.1
evals_per_epoch: 1
saves_per_epoch: 1
save_optimizer_states: false

deepspeed: configs/zero2.json

weight_decay: 0.0
special_tokens:
  pad_token: <|end_of_text|>
save_first_step: false  # uncomment this to validate checkpoint saving works with your config
