base_model: microsoft/Phi-3-medium-4k-instruct
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer 
trust_remote_code: true

load_in_8bit: false
load_in_4bit: false

chat_template: phi_3

special_tokens:
  eos_token: "<|end|>"
  
datasets:
  - path: data/axolotl/en-AU_Sarcasm_Reddit.jsonl
    type: chat_template
    # chat_template: phi_3
    roles_to_train: ["user", "assistant"] 
    train_on_eos: all
  - path: data/axolotl/en-IN_Sarcasm_Reddit.jsonl
    type: chat_template
    # chat_template: phi_3
    roles_to_train: ["user", "assistant"] 
    train_on_eos: all
  - path: data/axolotl/en-UK_Sarcasm_Reddit.jsonl
    type: chat_template
    # chat_template: phi_3
    roles_to_train: ["user", "assistant"] 
    train_on_eos: all

dataset_prepared_path: last_run_prepared
val_set_size: 0
output_dir:

model_config:
  output_router_logits: true

adapter: lora
lora_model_dir:

sequence_len: 512
sample_packing: true
pad_to_sequence_len: false

lora_r: 16
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 1
num_epochs: 5
optimizer: adamw_torch
lr_scheduler: cosine
learning_rate: 0.0002

bf16: true
tf32: false

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: True
resume_from_checkpoint:
logging_steps: 10
flash_attention: false

loss_watchdog_threshold: 5.0
loss_watchdog_patience: 3

warmup_ratio: 0.03
evals_per_epoch: 1
saves_per_epoch: 1
save_optimizer_states: false

deepspeed: configs/zero2.json

weight_decay: 0.0

save_first_step: false  # uncomment this to validate checkpoint saving works with your config